### ISSUE TITLE
Do we need the sun.misc bundle?

### ISSUE THREAD

**Issue by willrogers** [epics-rip/maven-osgi-bundles#38]
I had a lot of trouble making the pvaccess support work in CS-Studio.

After a while I realised that we don't need the `com.diffplug...sun.misc` bundle.  Instead you can add the property

`-Dorg.osgi.framework.system.packages.extra=sun.misc`

to your product instead and it will have the same effect.

**Comment by berryma4** [comment]
I just got an email from @kasemir, stating the same thing.
I vote for the property over the bundle.

**Comment by claudio-rosati** [comment]
I prefer property too... but... using sun.misc should be avoided and forbidden. In Java 9 probably it will not be available anymore.

**Comment by willrogers** [comment]
I believe the only requirement is in PVAccess.  It is (or should be) an optional dependency.  I can't see why it requires `sun.misc` anyway.  Does anyone know?

**Comment by kasemir** [comment]
I was under the impression that the dependency on sun.misc had been removed from pvaccess.

We're currently using org.epics.pvAccessJava_4.1.3.jar.
Kunal, @shroffk , is that an older pvaccess, so by updating to a newer one the sun.misc issue would go away?

**Comment by shroffk** [comment]
https://github.com/epics-base/pvAccessJava/commit/dd329bc800f00c415d0d4ad401d20ca1d0625d43

Should resolve the issues, however this has not been released...we might have to wait for the 5.1.0 version on pvaccess java
